# Basic
title: HarwordLiu的博客
subtitle: 程序猿一枚,现居北京
welcome_message: 欢迎来到Harword的技术博客
description: <p></p><p>长亭外</p><p>荒草蔓</p><p>烟雨任平生</p>
creator: <a href="http://harwordliu.com">@harword</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: rgb(151, 255, 255)

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看详细

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
#    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: RilmaHliu
    github: HarwordLiu
#    twitter: HarwordLiu
    mail: harry9391@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
